name: yaml CI
on:
  push:
    branches:
      - main

jobs:
  page-generator:
    name: 生产页面
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: 检查
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: 安装 NodeJS
        uses: actions/setup-node@main
        with:
          node-version: '14'
      - name: 安装依赖
        run: npm install
      - name: 构建页面
        run: npm run build
      - name: 部署站点
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.DEVELOP_DOC }}
          BRANCH: gh-pages
          FOLDER: dist
          COMMIT_MESSAGE: update from yaml
